#https://stackoverflow.com/questions/58065603/netlify-renders-404-on-page-refresh-using-react-and-react-router 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/ambient-token-list.json" 
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/rings_192.png"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[edge_functions]]
  path = "/*"
  function = "country-block"

# A redirect rule with many of the supported properties
[[redirects]]
  from = "/*"
  to = "/ambient-proven.netlify.app/:splat"

  status = 301

  # By default, redirects won’t be applied if there’s a file with the same
  # path as the one defined in the `from` property. Setting `force` to `true`
  # will make the redirect rule take precedence over any existing files.
  force = true

  # Redirect based on conditions including browser language, geolocation,
  # identity role, and/or cookie presence.
  conditions = {Country = ["NL"]}